In [59]:
from tatd2.utils import *
from tatd2.read import *
from tatd2.train import *
# from tatd2.tatd import *
from tatd2.alternating import *
from tatd2.als import *
# from tatd.als_opt import *

In [60]:
name = 'radar'
sparse = 0
rank = 10
window = 5
penalty = 10
opt_scheme = 'als_adam'
lr = 0.001
gpu = 0
count = 100

In [61]:
loss_path, model_path, total_path = get_path(name, sparse, 
                                            rank, window, penalty,
                                            opt_scheme, lr, count)

In [62]:

device = f'cuda:{gpu}'

dataset = read_dataset(name, device)
dataset['count'], dataset['window'] = count, window
nmode, ndim, tmode =  dataset['nmode'], dataset['ndim'], dataset['tmode']

density = dataset['ts_beta']

model = Tatd(nmode, ndim, tmode, density, rank, window, sparse, device).to(device)

In [63]:
factors = list(model.factors)

tidx = dataset['train'].indices()

nnz = krprod(factors, tidx)

In [64]:
nnz.shape

torch.Size([396548])

In [65]:
trai

NameError: name 'trai' is not defined

In [25]:
tidx

tensor([[    0,     0,     0,  ..., 17936, 17936, 17936],
        [    8,     8,     9,  ...,    15,    17,    17],
        [    1,     3,     1,  ...,     2,     0,     4]], device='cuda:0')

In [28]:
len(density)

17937

In [30]:
dataset['ndim']

torch.Size([17937, 23, 5])

In [32]:
tidx = 

tensor([[    0,     0,     0,  ..., 17936, 17936, 17936],
        [    8,     8,     9,  ...,    15,    17,    17],
        [    1,     3,     1,  ...,     2,     0,     4]], device='cuda:0')

# functions

In [46]:
rlambda = nn.Parameter(torch.FloatTensor(rng.random_sample(17937)))

In [50]:
tmp = krprod2(rlambda, factors, tidx)

tensor([[ 8.0772e-05, -7.5293e-05, -1.1253e-05,  ...,  1.9798e-04,
         -1.9992e-05, -6.1197e-04],
        [-1.3210e-04,  1.3708e-05,  5.1276e-05,  ..., -1.2411e-04,
         -6.2321e-05,  5.0403e-04],
        [-2.6103e-05,  2.5790e-05, -1.0906e-05,  ..., -9.3747e-05,
          6.3023e-05,  2.1188e-04],
        ...,
        [-3.3768e-05, -3.5480e-06,  2.2379e-04,  ..., -5.8253e-04,
          2.5756e-04,  8.5788e-04],
        [ 2.4150e-05,  5.3540e-06, -2.1570e-04,  ..., -8.9758e-04,
          3.2027e-04, -1.0246e-04],
        [-8.3603e-06,  7.1401e-06,  4.0463e-04,  ...,  2.0280e-04,
         -6.7350e-04, -1.8740e-04]], device='cuda:0')
tensor([[ 8.8435e-06, -8.2436e-06, -1.2321e-06,  ...,  2.1676e-05,
         -2.1889e-06, -6.7003e-05],
        [-1.4463e-05,  1.5009e-06,  5.6140e-06,  ..., -1.3588e-05,
         -6.8234e-06,  5.5185e-05],
        [-2.8580e-06,  2.8237e-06, -1.1940e-06,  ..., -1.0264e-05,
          6.9002e-06,  2.3198e-05],
        ...,
        [-3.6972e-06, -3.8847

In [58]:
tmp.shape

torch.Size([396548, 10])

In [56]:
tmp.sum(axis = 2).shape

IndexError: Dimension out of range (expected to be in range of [-2, 1], but got 2)

In [47]:
def krprod2(rlambda, factors, indices_list):

    ''' Khatri-rao product for given nonzeros' indicies '''

    rank = tl.shape(factors[0])[1]
    nnz = len(indices_list[0])
    nonzeros = tl.ones((nnz, rank), **tl.context(factors[0]))
    
    for indices, factor in zip(indices_list, factors):
        nonzeros = nonzeros * factor[indices, :]
    
    print(nonzeros)
    nonzeros = nonzeros * rlambda[indices[0]]
        
    print(nonzeros)
#     return torch.sum(nonzeros, dim = 1)
    return nonzeros

In [13]:
def krprod(factors, indices_list):

    ''' Khatri-rao product for given nonzeros' indicies '''

    rank = tl.shape(factors[0])[1]
    nnz = len(indices_list[0])
    nonzeros = tl.ones((nnz, rank), **tl.context(factors[0]))
    
    for indices, factor in zip(indices_list, factors):
        nonzeros = nonzeros * factor[indices, :]

#     return torch.sum(nonzeros, dim = 1)
    return nonzeros